#!/bin/sh
#
# Upgrade a machine.

set -e

machine="$1"

if ! [ "$machine" ]; then
    exit 1
fi

cd $machine

niv update

nixpkgs=$(nix eval '(let sources = import ./nix/sources.nix; in "${sources.nixpkgs}")' | tr -d '"')

sudo nixos-rebuild switch -I nixpkgs=$nixpkgs -I nixos=$nixpkgs -I nixos-config=/etc/nixos/configuration.nix
