{ config, pkgs, ... }:

{
  environment.systemPackages = with pkgs; [
    nix-index
    (emacs.override { withXwidgets = true; })
    neomutt
    offlineimap
    urlview
    ack
    file
    tmux
    screen
    stack
    imagemagick
    mpv
    mplayer
    vlc
    ffmpeg-full
    x264
    bento4
    firefox
    (chromium.override { enableVaapi = true; })
    surf
    usbutils
    terminator
    zathura
    evince
    rustup
    pavucontrol
    sox
    whois
    wget
    go-mtpfs
    git
    syncplay
    calibre
    tightvnc
    gcc
    clang
    binutils
    gnumake
    cmake
    stdmanpages
    manpages
    valgrind
    stalonetray
    nmap
    gnupg
    bash-completion
    wmctrl
    autossh
    sshfs
    pandoc
    htop
    iotop
    nload
    pciutils
    youtube-dl
    transmission-remote-gtk
    acpi
    dtrx
    rdiff-backup
    zip
    unzip
    iw
    gimp
    inkscape
    texlive.combined.scheme-full
    w3m
    lynx
    aalib
    libreoffice
    gpicview
    toilet
    bc
    ascii
    swiProlog
    tree
    aegisub
    gparted
    feh
    gnome3.nautilus
    gnum4
    automake
    autoconf
    libtool
    socat
    audacity
    gnuapl
    mediainfo
    bind
    bat
    rclone
    zile
    gnome3.cheese
    xawtv
    gnome3.dconf-editor
    xorg.xmodmap
    xorg.setxkbmap
    xorg.xsetroot
    xorg.xrandr
    xorg.xdpyinfo
    xorg.xeyes
    xorg.xhost
    xdotool
    xsel
    xmacro
    (python27.withPackages (ps: with ps; [ numpy pygtk ]))
    (python3.withPackages (ps: with ps; [ numpy setuptools requests termcolor pyyaml pygments ]))
    ocaml
    opam
    ocamlPackages.base
    ocamlPackages.findlib
    dune
    ntfs3g
    exfat-utils
    baobab
    lm_sensors
    signal-desktop
    pngcrush
    glxinfo
    cudatoolkit
    element-desktop
    qjackctl
    supercollider
    supercollider_scel
    jitsi-meet-electron

    # unfree
    spotify
    steam
    slack
    google-chrome
    discord
  ];
}
